# Используем образ с Node.js
image: node:20-alpine

# Определение стадий конвейера
stages:
  - install
  - lint
  - test
  - build

# Кэширование зависимостей для ускорения сборки
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
    - node_modules/
    - /root/.npm # Кэшируем глобальные npm пакеты
  policy: pull-push # Явно указываем политику кэша: загружать и обновлять

# Настраиваем pnpm один раз для всего пайплайна
before_script:
  - npm install -g pnpm
  - pnpm config set store-dir .pnpm-store

# Установка зависимостей
install:
  stage: install
  script:
    - pnpm install

# Проверка кода линтерами
lint:
  stage: lint
  script:
    - pnpm lint:ts
    - pnpm lint:scss
  # Удаляем dependencies, так как будем использовать кэш

# Запуск тестов
test:
  stage: test
  script:
    - pnpm test
  # Удаляем dependencies, так как будем использовать кэш

# Сборка проекта
build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
  # Удаляем dependencies, так как будем использовать кэш
  only:
    - main
    - develop