spec:
  inputs:
    node_version:
      description: "Версия Node.js для использования в CI/CD"
      default: "20-alpine"
      options: ["16-alpine", "18-alpine", "20-alpine"]
    run_lint:
      description: "Запускать ли проверку линтером"
      type: boolean
      default: true
    run_tests:
      description: "Запускать ли тесты"
      type: boolean
      default: true
    cache_key:
      description: "Ключ для кэширования зависимостей"
      default: "${CI_COMMIT_REF_SLUG}"

---

# Базовый образ для всех заданий
image: node:$[[ inputs.node_version ]]

# Определение стадий конвейера
stages:
  - install
  - lint
  - test
  - build

# Кэширование зависимостей для ускорения сборки
cache:
  key: $[[ inputs.cache_key ]]
  paths:
    - .pnpm-store
    - node_modules/

# Установка зависимостей
install:
  stage: install
  script:
    - npm install -g pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  artifacts:
    paths:
      - node_modules/

# Проверка кода линтерами
lint:
  stage: lint
  script:
    - pnpm lint:ts
    - pnpm lint:scss
  dependencies:
    - install
  rules:
    - if: '$[[ inputs.run_lint ]] == "true"'
      when: always
    - when: never

# Запуск тестов
test:
  stage: test
  script:
    - pnpm test
  dependencies:
    - install
  rules:
    - if: '$[[ inputs.run_tests ]] == "true"'
      when: always
    - when: never

# Сборка проекта
build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
  dependencies:
    - install