# Используем образ с Node.js
image: node:20-alpine

# Определение стадий конвейера
stages:
  - install
  - lint
  - test
  - build

# Кэширование зависимостей для ускорения сборки
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
    - node_modules/
    - /root/.npm # Кэшируем глобальные npm пакеты

# Настраиваем pnpm один раз для всего пайплайна
before_script:
  - npm install -g pnpm
  - pnpm config set store-dir .pnpm-store

# Установка зависимостей
install:
  stage: install
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/

# Проверка кода линтерами
lint:
  stage: lint
  script:
    - pnpm lint:ts
    - pnpm lint:scss
  dependencies:
    - install

# Запуск тестов
test:
  stage: test
  script:
    - pnpm test
  dependencies:
    - install

# Сборка проекта
build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
  dependencies:
    - install
  only:
    - main
    - develop