#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 1. Проверяем только измененные файлы с помощью git diff
STAGED_TS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep "\.tsx\?$" || true)
STAGED_SCSS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep "\.scss$" || true)

# 2. Запускаем линтеры только если есть соответствующие измененные файлы
if [ -n "$STAGED_TS_FILES" ]; then
  echo "🔍 Проверка TS файлов..."
  pnpm eslint $STAGED_TS_FILES --cache --fix || exit 1
else
  echo "✅ Нет измененных TS файлов для проверки"
fi

if [ -n "$STAGED_SCSS_FILES" ]; then
  echo "🔍 Проверка SCSS файлов..."
  pnpm stylelint $STAGED_SCSS_FILES --cache --fix || exit 1
else
  echo "✅ Нет измененных SCSS файлов для проверки"
fi


echo "✨ Pre-commit проверки успешно пройдены!"
